# Generated by Django 4.2.5 on 2023-09-28 12:37

from django.db import migrations
from django.db.migrations import RunPython

from django.core.management import call_command


def func(apps, schema_editor):
    user = apps.get_model('cosmetics', 'Member')
    user.objects.create_superuser(
        username='admin',
        password='admin',
        email='admin@admin.com'
    )
    call_command('loaddata', 'fixture_data.json')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("cosmetics", "0001_initial"),
    ]

    operations = [
        RunPython(func, reverse_func),
    ]
